from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path
from typing import Iterable

from openpyxl import load_workbook

from .models import DeviceRecord, EquipmentGroup, ProjectDefaults


VAV_SD_PARAMETERS = [
    ("SA-AREA", "AV3111", "Default Value", "sa_area"),
    ("SA-KFACTOR", "AV3112", "Default Value", "sa_kfactor"),
    ("CLG-MAXFLOW", "AV3108", "Default Value", "clg_maxflow"),
    ("CLGOCC-MINFLOW", "AV3109", "Default Value", "clg_minflow"),
    ("HTGOCC-MINFLOW", "AV3110", "Default Value", "htg_minflow"),
]


def generate_equipment_name(prefix: str, separator: str, number: int, digits: int) -> str:
    prefix = prefix.strip()
    if not prefix:
        raise ValueError("Equipment prefix cannot be blank.")
    if digits < 1:
        raise ValueError("Digits must be at least 1.")
    return f"{prefix}{separator}{number:0{digits}d}"


def build_device_description(device_name: str, leaf_space: str, room_number: str) -> str:
    device_name = device_name.strip()
    leaf_space = leaf_space.strip()
    room_number = room_number.strip()
    if not leaf_space:
        return device_name
    description = f"{device_name} - {leaf_space}"
    if room_number:
        description += f" Rm {room_number}"
    return description


def _engine_suffix(engine_name: str) -> str:
    match = re.search(r"(\d{2})\s*$", engine_name.strip())
    if not match:
        raise ValueError("Engine name must end in two digits (example: S3-SNE03).")
    return match.group(1)


def _trunk_suffix(trunk_name: str) -> str:
    match = re.search(r"(\d)\s*$", trunk_name.strip())
    if not match:
        raise ValueError("Trunk name must end in a digit (example: FC-1).")
    return match.group(1)


def generate_bacnet_instance(
    engine_name: str,
    trunk_name: str,
    mac_address: int | None,
    ip_controller_number: int | None,
) -> int:
    """Reproduce the project convention used by the supplied RAC scratchpad."""
    if mac_address is not None and ip_controller_number is not None:
        raise ValueError("MAC and IP Controller Number cannot both have values.")
    address = mac_address if mac_address is not None else ip_controller_number
    if address is None:
        raise ValueError("A MAC address or IP Controller Number is required to generate an instance.")
    engine = int(_engine_suffix(engine_name))
    trunk = _trunk_suffix(trunk_name)
    base_prefix = 1000 + engine
    base = int(f"{base_prefix}{trunk}00")
    return base + int(address)


def generate_fqr(engine_name: str, trunk_name: str, controller_part: str, instance: int) -> str:
    """Reproduce the custom FQR convention found in the supplied workbook."""
    engine = _engine_suffix(engine_name)
    trunk = _trunk_suffix(trunk_name)
    controller_part = controller_part.strip()
    if len(controller_part) < 5:
        raise ValueError("Controller Part # is too short to generate the custom FQR.")
    controller_code = controller_part[3:5]
    return f"{engine}{trunk}{controller_code}0{str(instance)[-2:].zfill(2)}"


def infer_heat_flags(controller_template: str) -> tuple[bool | None, bool | None]:
    template = controller_template.strip()
    if not template:
        return None, None
    box_heat = template != "VAV-CLG"
    supplemental = template == "VAV-RAD"
    return box_heat, supplemental


def split_served_by(value: str) -> list[str]:
    """Return individual SCT Served By equipment names (SCT uses && for multiple parents)."""
    return [part.strip() for part in value.split("&&") if part.strip()]


def normalize_existing_equipment(value: str | Iterable[str]) -> set[str]:
    if isinstance(value, str):
        parts = re.split(r"[\n,;]+", value)
    else:
        parts = list(value)
    return {str(part).strip() for part in parts if str(part).strip()}


def build_dependency_levels(
    records: Iterable[DeviceRecord],
    existing_equipment: str | Iterable[str] = (),
) -> list[list[DeviceRecord]]:
    """Build top-down SCT import levels from Served By relationships.

    Parents generated by this project must be in an earlier level. Parents declared in
    ``existing_equipment`` are considered already present in SCT and do not create a
    project-level dependency.
    """
    records = list(records)
    existing = normalize_existing_equipment(existing_equipment)
    by_name: dict[str, DeviceRecord] = {}
    for record in records:
        name = record.equipment_name.strip()
        if name and name not in by_name:
            by_name[name] = record

    dependencies: dict[str, set[str]] = {}
    for name, record in by_name.items():
        deps = {
            parent
            for parent in split_served_by(record.served_by)
            if parent in by_name and parent not in existing
        }
        dependencies[name] = deps

    remaining = set(by_name)
    completed: set[str] = set()
    levels: list[list[DeviceRecord]] = []
    while remaining:
        ready = sorted(
            [name for name in remaining if dependencies[name] <= completed],
            key=str.casefold,
        )
        if not ready:
            cycle = ", ".join(sorted(remaining, key=str.casefold))
            raise ValueError(f"Circular Served By relationship detected among: {cycle}")
        levels.append([by_name[name] for name in ready])
        completed.update(ready)
        remaining.difference_update(ready)

    # Preserve additional rows for the same equipment directly after its first row.
    extras: dict[str, list[DeviceRecord]] = defaultdict(list)
    seen_first: set[str] = set()
    for record in records:
        name = record.equipment_name.strip()
        if name in seen_first:
            extras[name].append(record)
        else:
            seen_first.add(name)
    for level in levels:
        expanded: list[DeviceRecord] = []
        for record in level:
            expanded.append(record)
            expanded.extend(extras.get(record.equipment_name.strip(), []))
        level[:] = expanded
    return levels


def ordered_records_for_sct(
    records: Iterable[DeviceRecord], existing_equipment: str | Iterable[str] = ()
) -> list[DeviceRecord]:
    return [record for level in build_dependency_levels(records, existing_equipment) for record in level]


def validate_records_for_sct(
    records: Iterable[DeviceRecord],
    existing_equipment: str | Iterable[str] = (),
) -> tuple[list[str], list[str]]:
    """Validate fields and relationships that matter to SCT Rapid Archive.

    Returns ``(errors, warnings)``. Warnings are conditions that may be legitimate but
    should be confirmed in SCT before import.
    """
    records = list(records)
    existing = normalize_existing_equipment(existing_equipment)
    errors: list[str] = []
    warnings: list[str] = []

    if not records:
        return ["No devices have been generated."], []

    required = {
        "Site/Building/Floor": "site_hierarchy",
        "Device Name": "device_name",
        "Device FQR Reference": "fqr",
        "Equipment Name": "equipment_name",
        "Engine Name": "engine_name",
        "Trunk Name": "trunk_name",
        "Controller Template Name": "controller_template",
    }
    for index, record in enumerate(records, start=1):
        label = record.equipment_name or record.device_name or f"row {index}"
        for display, field_name in required.items():
            if not str(getattr(record, field_name) or "").strip():
                errors.append(f"{label}: {display} is required for this generator's SCT workflow.")
        if not record.leaf_space.strip():
            warnings.append(
                f"{label}: Leaf Space is blank. This is only expected when the equipment serves the whole campus/site."
            )
        if record.mac_address is not None and not 4 <= record.mac_address <= 127:
            errors.append(f"{label}: JCI MS/TP MAC address must be between 4 and 127.")
        if record.instance is not None and not 0 <= record.instance <= 4_194_302:
            errors.append(f"{label}: BACnet Instance must be between 0 and 4,194,302.")

    duplicates = find_duplicate_values(records)
    for field, values in duplicates.items():
        formatted = ", ".join(map(str, sorted(values, key=str)))
        if field == "Equipment Name":
            warnings.append(
                f"Repeated Equipment Name(s): {formatted}. This is valid only when one controller/equipment pairing intentionally spans multiple rows."
            )
        else:
            errors.append(f"Duplicate {field}(s): {formatted}")

    # MAC uniqueness is scoped to engine + trunk, not globally.
    seen_mac: dict[tuple[str, str, int], str] = {}
    for record in records:
        if record.mac_address is None:
            continue
        key = (record.engine_name.strip(), record.trunk_name.strip(), record.mac_address)
        previous = seen_mac.get(key)
        if previous and previous != record.device_name:
            errors.append(
                f"Duplicate MS/TP address {record.mac_address} on {record.engine_name}/{record.trunk_name}: "
                f"{previous} and {record.device_name}."
            )
        else:
            seen_mac[key] = record.device_name

    generated_names = {r.equipment_name.strip() for r in records if r.equipment_name.strip()}
    for record in records:
        for parent in split_served_by(record.served_by):
            if parent not in generated_names and parent not in existing:
                errors.append(
                    f"{record.equipment_name}: Served By '{parent}' is neither generated by this project nor listed as already existing in SCT."
                )

    try:
        build_dependency_levels(records, existing)
    except ValueError as exc:
        errors.append(str(exc))

    if any(r.ip_controller_number is not None for r in records):
        warnings.append(
            "IP controller support is still partial: verify DHCP/static IP settings and IP addresses in SCT before saving the Rapid Archive wizard."
        )

    return _dedupe(errors), _dedupe(warnings)


def _dedupe(values: Iterable[str]) -> list[str]:
    seen = set()
    result = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


def load_manufacturer_data(template_path: str | Path) -> dict[str, dict[int, tuple[float | None, float | None]]]:
    wb = load_workbook(template_path, data_only=True, read_only=True)
    ws = wb["Manufacturer"]
    manufacturers: dict[str, dict[int, tuple[float | None, float | None]]] = {}
    for area_col in range(4, 38, 2):
        name = ws.cell(row=25, column=area_col).value
        if not name:
            continue
        display_name = str(name).split("\n", 1)[0].strip()
        records: dict[int, tuple[float | None, float | None]] = {}
        for row in range(28, 46):
            size = ws.cell(row=row, column=2).value
            if size is None:
                continue
            try:
                size_int = int(size)
            except (TypeError, ValueError):
                continue
            area = ws.cell(row=row, column=area_col).value
            kfactor = ws.cell(row=row, column=area_col + 1).value
            numeric = lambda value: float(value) if isinstance(value, (int, float)) else None
            records[size_int] = (numeric(area), numeric(kfactor))
        manufacturers[display_name] = records
    wb.close()
    return manufacturers


def manufacturer_lookup(
    manufacturer_data: dict[str, dict[int, tuple[float | None, float | None]]],
    manufacturer: str,
    inlet_size: int | None,
) -> tuple[float | None, float | None]:
    if inlet_size is None:
        return None, None
    return manufacturer_data.get(manufacturer, {}).get(int(inlet_size), (None, None))


def recalculate_record(
    record: DeviceRecord,
    manufacturer_data: dict[str, dict[int, tuple[float | None, float | None]]],
    generate_instance: bool = True,
    fqr_mode: str = "Device Name (SCT recommended)",
) -> DeviceRecord:
    record.device_description = build_device_description(record.device_name, record.leaf_space, record.room_number)
    record.box_heat, record.supplemental_heat = infer_heat_flags(record.controller_template)
    record.sa_area, record.sa_kfactor = manufacturer_lookup(
        manufacturer_data, record.manufacturer, record.inlet_size
    )

    if generate_instance:
        try:
            record.instance = generate_bacnet_instance(
                record.engine_name, record.trunk_name, record.mac_address, record.ip_controller_number
            )
        except ValueError:
            record.instance = None
    else:
        record.instance = None

    if fqr_mode.startswith("Device Name"):
        record.fqr = record.device_name.strip()
    elif fqr_mode.startswith("Custom workbook"):
        if record.instance is not None:
            try:
                record.fqr = generate_fqr(
                    record.engine_name, record.trunk_name, record.controller_part, record.instance
                )
            except ValueError:
                record.fqr = ""
        else:
            record.fqr = ""
    else:
        record.fqr = record.fqr.strip() or record.device_name.strip()

    record.parameters = {
        "SA-AREA": record.sa_area,
        "SA-KFACTOR": record.sa_kfactor,
        "CLG-MAXFLOW": record.clg_maxflow,
        "CLGOCC-MINFLOW": record.clg_minflow,
        "HTGOCC-MINFLOW": record.htg_minflow,
    }
    return record


def generate_group_records(
    defaults: ProjectDefaults,
    group: EquipmentGroup,
    manufacturer_data: dict[str, dict[int, tuple[float | None, float | None]]],
) -> list[DeviceRecord]:
    if group.end < group.start:
        raise ValueError("Ending number must be greater than or equal to the starting number.")
    if group.digits < 1:
        raise ValueError("Digits must be at least 1.")
    if group.start_address < 0:
        raise ValueError("Starting MAC/IP Controller Number cannot be negative.")

    records: list[DeviceRecord] = []
    for offset, number in enumerate(range(group.start, group.end + 1)):
        equipment_name = generate_equipment_name(group.equipment_prefix, group.separator, number, group.digits)
        device_name = f"{defaults.device_prefix}{equipment_name}"
        address = group.start_address + offset
        record = DeviceRecord(
            site_hierarchy=defaults.site_hierarchy,
            device_name=device_name,
            equipment_name=equipment_name,
            served_by=group.served_by,
            controller_part=defaults.controller_part,
            engine_name=defaults.engine_name,
            trunk_name=defaults.trunk_name,
            equipment_definition=defaults.equipment_definition,
            controller_template=defaults.controller_template,
            dhcp_enabled=defaults.dhcp_enabled if defaults.network_type == "IP" else None,
            subnet_mask=defaults.subnet_mask if defaults.network_type == "IP" else "",
            ip_router=defaults.ip_router if defaults.network_type == "IP" else "",
            manufacturer=group.manufacturer,
            inlet_size=group.inlet_size,
            clg_maxflow=group.clg_maxflow,
            clg_minflow=group.clg_minflow,
            htg_minflow=group.htg_minflow,
        )
        if defaults.network_type == "MSTP":
            record.mac_address = address
        else:
            record.ip_controller_number = address
        recalculate_record(record, manufacturer_data, defaults.generate_instance, defaults.fqr_mode)
        records.append(record)
    return records


def find_duplicate_values(records: Iterable[DeviceRecord]) -> dict[str, set[object]]:
    records = list(records)
    fields = {
        "Equipment Name": [r.equipment_name for r in records if r.equipment_name],
        "Device Name": [r.device_name for r in records if r.device_name],
        "FQR": [r.fqr for r in records if r.fqr],
        "Instance": [r.instance for r in records if r.instance is not None],
    }
    duplicates: dict[str, set[object]] = {}
    for label, values in fields.items():
        seen = set()
        dupes = set()
        for value in values:
            if value in seen:
                dupes.add(value)
            seen.add(value)
        if dupes:
            duplicates[label] = dupes
    return duplicates
